[connections.supabase]
SUPABASE_URL = "https://dlkufzkqezrjdoxzszob.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsa3VmemtxZXpyamRveHpzem9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkyMzY3MjIsImV4cCI6MjA4NDgxMjcyMn0.dy32N2j0RzoLlft_S9622i9F3zjtH6rf1rLwTULviYs"